FROM node:16-alpine as build

WORKDIR /app
ENV PATH /app/node_modules/.bin:$PATH

COPY package.json /app/package.json
RUN npm install

COPY src/ /app/src
COPY public/ /app/public

CMD ["npm", "start"]
