FROM python:3.8-alpine

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1
ENV PATH /usr/src/app:$PATH

WORKDIR /usr/src/app

COPY middleware/requirements.txt /usr/src/app/
RUN pip install --no-cache-dir --upgrade pip
RUN pip install --no-cache-dir -r requirements.txt

COPY middleware/ /usr/src/app/

CMD ["flask", "run", "--host=0.0.0.0"]
